# Generated by Django 3.2.11 on 2022-03-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
