# Generated by Django 3.2.12 on 2022-02-28 09:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(max_length=250, verbose_name='entidad')),
                ('domicilio', models.CharField(max_length=250)),
                ('c_p', models.DecimalField(decimal_places=1, max_digits=6)),
                ('localidad', models.CharField(max_length=250)),
                ('horario', models.CharField(max_length=250)),
                ('web', models.URLField(blank=True)),
                ('telefono', models.CharField(max_length=250)),
                ('fax', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Federación deportiva',
                'verbose_name_plural': 'Federaciones deportivas',
            },
        ),
        migrations.CreateModel(
            name='DeportesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduccion', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
