# Generated by Django 3.2.12 on 2022-02-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0005_auto_20220208_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
